### ISSUE TITLE
npm i fails with shrinkwrap on Debian 8 x32

### ISSUE THREAD

**Issue by christiandreher** [mozilla/fxa-auth-db-mysql#188]
When I try to run `npm i` it fails with the following undescriptive error messages:

```bash
npm ERR! Linux 3.16.0-4-686-pae
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'glob' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.16.0-4-686-pae
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'lodash.keys' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.16.0-4-686-pae
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'lodash.keys' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fxcloud/fxa-auth-db-mysql/npm-debug.log
```

`npm-debug.log` contains the following at the end:

```bash
35690 verbose stack TypeError: Cannot read property 'glob' of undefined
35690 verbose stack     at /usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:35:40
35690 verbose stack     at Array.filter (native)
35690 verbose stack     at inflateShrinkwrap (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:34:49)
35690 verbose stack     at /usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:16
35690 verbose stack     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:13:50
35690 verbose stack     at zalgoSafe (/usr/lib/node_modules/npm/node_modules/dezalgo/dezalgo.js:20:10)
35690 verbose stack     at finalize (/usr/lib/node_modules/npm/node_modules/realize-package-specifier/index.js:39:5)
35690 verbose stack     at /usr/lib/node_modules/npm/node_modules/realize-package-specifier/index.js:22:20
35690 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:276:29
35690 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
35691 verbose cwd /home/fxcloud/fxa-auth-db-mysql
35692 error Linux 3.16.0-4-686-pae
35693 error argv "/usr/bin/nodejs" "/usr/bin/npm" "i"
35694 error node v6.9.1
35695 error npm  v4.0.2
35696 error Cannot read property 'glob' of undefined
35697 error If you need help, you may report this error at:
35697 error     <https://github.com/npm/npm/issues>
35698 verbose exit [ 1, true ]
```

More information:

- When deleting `npm-shrinkwrap.json`, the install succeded, but I am not sure if the correct dependencies are installed now
- I tried `master` and the tag `v0.74.0`, same outcome
- Output `lsb_release -a`
```bash
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.6 (jessie)
Release:	8.6
Codename:	jessie
```
- Output `uname -m`(architecture): `i686` (32 bit)
- Output `node -v`: `v6.9.1`
- Output `npm -v`: `4.0.2`
- As of 11/20/2016, all packages are up-to-date

If you need more information, let me know

_______________

**Update**

I did the following:

```bash
cd <repo path>
rm npm-shrinkwrap.json
npm i
git reset --hard
npm test
```

This is the output:

```bash
> fxa-auth-db-mysql@0.74.0 test /home/fxcloud/fxa-auth-db-mysql
> npm run test-mysql && npm run test-mem && npm run test-server


> fxa-auth-db-mysql@0.74.0 test-mysql /home/fxcloud/fxa-auth-db-mysql
> grunt && node ./bin/db_patcher.js >/dev/null && ./scripts/tap-coverage.js test/backend test/local

Running "eslint:files" (eslint) task

Running "copyright:app" (copyright) task

Running "copyright:tests" (copyright) task

Done.

npm ERR! Linux 3.16.0-4-686-pae
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test-mysql"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! fxa-auth-db-mysql@0.74.0 test-mysql: `grunt && node ./bin/db_patcher.js >/dev/null && ./scripts/tap-coverage.js test/backend test/local`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the fxa-auth-db-mysql@0.74.0 test-mysql script 'grunt && node ./bin/db_patcher.js >/dev/null && ./scripts/tap-coverage.js test/backend test/local'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fxa-auth-db-mysql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt && node ./bin/db_patcher.js >/dev/null && ./scripts/tap-coverage.js test/backend test/local
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fxa-auth-db-mysql
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fxa-auth-db-mysql
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fxcloud/fxa-auth-db-mysql/npm-debug.log
npm ERR! Test failed.  See above for more details.
```

Though that the error message claims that it created a `npm-debug.log`, there is none.

**Comment by vladikoff** [comment]
try with node 4 and npm 2

**Comment by christiandreher** [comment]
Before I had this error, I was installing `fxa-auth-server`, which succeded (after some minor issues). In this process, I've updated `npm` to `4.0.2`. After I encountered the error described in this issue, I tried it on `fxa-auth-server` again, and got the same issue. After that, I downgraded `npm` to `3.10.9`, tried installing `fxa-auth-server` *again*, and got the same minor issues mentioned above...

So with `npm@3.10.9` i tried installing `fxa-auth-db-mysql` again and it worked without problems. After that, I upgraded `npm` to `4.0.2` again and was able to install `fxa-auth-server` like before.

@vladikoff thanks for pointing me to the right direction, but I am unable to downgrade `node` and `npm` so drastically, as other software on my server depends on it unfortunately...

I hope that `npm@4.0.x` will be supported eventually, since this error was really really nasty to debug. However, you could update the prerequisites in `README.md`, since the only requirement which is mentioned there is "Node.js 0.10 or later".

Anyway I will close this issue now, and thank you very much again for your help.

**Comment by jrgm** [comment]
Apologies for the documentation not being explicitly clear. 

As for fairly easily running alternate versions of `node` and `npm`, I highly recommend https://github.com/creationix/nvm
