### ISSUE TITLE
lib/db/mysql.js - unhandled TypeError when running on an fxa-dev box

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-db-mysql#49]
Noticed that the auth-db-mysql server on an fxa-dev is filling its logs with the exception below. 

I believe that this is due to the change from p-promise to bluebird, and that [this function](https://github.com/mozilla/fxa-auth-db-mysql/blob/master/bin/server.js#L51-L58) should ensure that it always returns a promise on any path (events or no events), (`P.resolve()`?).

```
Possibly unhandled TypeError: Cannot call method 'then' of undefined
    at query.then.then.log.error.op (/data/fxa-auth-db-mysql/lib/db/mysql.js:734:20)
    at tryCatch1 (/data/fxa-auth-db-mysql/node_modules/bluebird/js/main/util.js:43:21)
    at Promise$_callHandler [as _callHandler] (/data/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:627:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/data/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:641:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/data/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:800:14)
    at Promise$_settlePromises [as _settlePromises] (/data/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:934:14)
    at Promise.b (domain.js:183:18)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/data/fxa-auth-db-mysql/node_modules/bluebird/js/main/async.js:75:12)
    at Async$consumeFunctionBuffer (/data/fxa-auth-db-mysql/node_modules/bluebird/js/main/async.js:38:14)
    at process._tickDomainCallback (node.js:492:13)
```

**Comment by chilts** [comment]
Yeah, looks like it.
